#!/usr/bin/env python3
"""Cross-run summary for Experiment B (no CARLA access; reads saved run outputs).

Run 3 is the canonical output in this directory; runs 1 and 2 are archived under
evidence/runs/. Writes runs_comparison.csv and inserts a generated section into
continuous_10min_report.md between fixed markers.
"""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path


HERE = Path(__file__).resolve().parent
RUNS = (
    ("run1", HERE / "evidence" / "runs" / "run1", "vlm_trigger_events.csv"),
    ("run2", HERE / "evidence" / "runs" / "run2", "vlm_trigger_events.csv"),
    ("run3", HERE, "vlm_trigger_events.csv"),
)
BRANCHES = ("full", "no_hsv", "no_temporal", "no_dedup")
TITLES = {"full": "Full", "no_hsv": "No HSV", "no_temporal": "No Temporal", "no_dedup": "No Dedup"}
BEGIN = "<!-- BEGIN repeated-runs (generated by compare_runs.py) -->"
END = "<!-- END repeated-runs -->"


def read_csv(path):
    with Path(path).open(encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def load_run(name, directory, events_name):
    ablation = {row["branch"]: row for row in read_csv(directory / "ablation_summary.csv")}
    events = read_csv(directory / events_name)
    result_path = directory / "evidence" / "result.json" if name == "run3" else directory / "result.json"
    result = json.loads(result_path.read_text(encoding="utf-8"))
    frames_path = directory / "evidence" / "frame_metrics.csv" if name == "run3" else directory / "frame_metrics.csv"
    target_trigger_actors = {
        branch: len({e["actor_id"] for e in events if e["branch"] == branch and e["target_color_state"] == "target_actor"})
        for branch in BRANCHES
    }
    return {"name": name, "ablation": ablation, "common": result["common"], "frames": read_csv(frames_path),
            "target_trigger_actors": target_trigger_actors}


def build_rows(runs):
    rows = []
    for run in runs:
        for branch in BRANCHES:
            row = run["ablation"][branch]
            rows.append({
                "run": run["name"], "branch": branch,
                "vlm_triggers": int(row["vlm_triggers"]),
                "vs_full_increase": int(row["vs_full_increase"]),
                "vs_full_ratio": row["vs_full_ratio"],
                "candidates_raised": int(row["candidates_raised"]),
                "duplicate_suppressed": int(row["duplicate_suppressed"]),
                "triggers_target_actor": int(row["triggers_target_actor"]),
                "triggers_non_target_actor": int(row["triggers_non_target_actor"]),
                "triggers_unassociated": int(row["triggers_unassociated"]),
                "target_actors_with_vlm_trigger": run["target_trigger_actors"][branch],
                "vlm_triggers_from_disappeared_tracks": row.get("vlm_triggers_from_disappeared_tracks", ""),
                "input_frames": run["common"]["input_frames"],
                "unique_vehicles_entering_fov": run["common"]["unique_vehicles_entering_fov"],
                "target_color_vehicles_entering_fov": run["common"]["target_color_vehicles_entering_fov"],
                "total_yolo_vehicle_detections": run["common"]["total_yolo_vehicle_detections"],
            })
    return rows


def divergence(reference, other):
    gt_keys = ("projected_vehicles", "visible_vehicles", "visible_target_vehicles")
    traffic = next((i for i, (a, b) in enumerate(zip(reference, other))
                    if any(a[k] != b[k] for k in gt_keys)), None)
    yolo = next((i for i, (a, b) in enumerate(zip(reference, other))
                 if a["yolo_detections"] != b["yolo_detections"]), None)
    return yolo, traffic


def section(runs, rows):
    by = {(row["run"], row["branch"]): row for row in rows}
    names = [run["name"] for run in runs]
    lines = [BEGIN, "", "## Repeated 10-minute runs (Run 1, Run 2, Run 3)", "",
             "Three independent full 10-minute runs with the same seed, spawn plan, camera and branch",
             "logic. Within each run the four branches share identical frames and detections; across",
             "runs, CARLA rendering/inference and Traffic Manager traffic are not bit-identical (see",
             "divergence below), so each run is a separate sample. Run 3 is the canonical output in",
             "this directory; runs 1-2 are in `evidence/runs/`. Run 1 predates the bbox/crop and",
             "disappeared-track fields (same branch and scene logic); Run 2 predates the",
             "disappeared-track field.", "",
             "| Configuration | " + " | ".join("{0} triggers (vs Full)".format(n.title()) for n in names)
             + " | Min-max |", "|---|" + "---:|" * (len(names) + 1)]
    for branch in BRANCHES:
        cells = []
        values = []
        for name in names:
            row = by[(name, branch)]
            values.append(row["vlm_triggers"])
            cells.append("{0} ({1})".format(row["vlm_triggers"], "1.00x" if branch == "full" else "{0:+d}, {1:.2f}x".format(
                row["vs_full_increase"], float(row["vs_full_ratio"]))))
        lines.append("| {0} | {1} | {2}-{3} |".format(TITLES[branch], " | ".join(cells), min(values), max(values)))
    lines += ["", "Candidates before dedup and what the triggers hit (actor association is evidence only):", "",
              "| Run | Branch | Candidates | Dedup-suppressed | Triggers: target / non-target / unassociated | Distinct target actors reaching VLM | Triggers from disappeared tracks |",
              "|---|---|---:|---:|---|---:|---:|"]
    for name in names:
        for branch in BRANCHES:
            row = by[(name, branch)]
            lines.append("| {0} | {1} | {2} | {3} | {4} / {5} / {6} | {7} of {8} | {9} |".format(
                name, TITLES[branch], row["candidates_raised"], row["duplicate_suppressed"],
                row["triggers_target_actor"], row["triggers_non_target_actor"], row["triggers_unassociated"],
                row["target_actors_with_vlm_trigger"], row["target_color_vehicles_entering_fov"],
                row["vlm_triggers_from_disappeared_tracks"] if row["vlm_triggers_from_disappeared_tracks"] != "" else "n/r"))
    lines += ["", "Traffic per run:", "", "| Run | Input frames | Unique vehicles in FOV | Target-colour in FOV | YOLO detections |",
              "|---|---:|---:|---:|---:|"]
    for run in runs:
        common = run["common"]
        lines.append("| {0} | {1} | {2} | {3} | {4} |".format(
            run["name"], common["input_frames"], common["unique_vehicles_entering_fov"],
            common["target_color_vehicles_entering_fov"], common["total_yolo_vehicle_detections"]))
    lines += ["", "Run-to-run divergence (first differing frame vs Run 1):", ""]
    for run in runs[1:]:
        yolo, traffic = divergence(runs[0]["frames"], run["frames"])
        lines.append("- {0}: YOLO count first differs at frame {1}; ground-truth traffic first differs at frame {2}.".format(
            run["name"], yolo, traffic))
    full = [by[(n, "full")]["vlm_triggers"] for n in names]
    no_dedup = [by[(n, "no_dedup")]["vlm_triggers"] for n in names]
    no_hsv = [by[(n, "no_hsv")]["vlm_triggers"] for n in names]
    lines += [
        "", "## Findings (ablation comparison on identical input per run; not causal claims)", "",
        "- Deduplication: removing it raised VLM triggers from {0} to {1} across runs".format(
            "/".join(map(str, full)), "/".join(map(str, no_dedup))),
        "  (mean {0:.1f} vs {1:.1f}). Production dedup is a 30 s cooldown per camera agent, so".format(
            statistics.mean(full), statistics.mean(no_dedup)),
        "  every dedup branch is bounded by about 20 triggers per 10 minutes regardless of traffic.",
        "- HSV: removing it raised triggers from {0} to {1}; its larger effect is upstream:".format(
            "/".join(map(str, full)), "/".join(map(str, no_hsv))),
        "  candidates before dedup grew from {0} to {1}, and the cooldown was then consumed by".format(
            "/".join(str(by[(n, 'full')]["candidates_raised"]) for n in names),
            "/".join(str(by[(n, 'no_hsv')]["candidates_raised"]) for n in names)),
        "  non-target and unassociated detections (target-actor triggers: {0}).".format(
            "/".join(str(by[(n, 'no_hsv')]["triggers_target_actor"]) for n in names)),
        "- Temporal Confirmation: under the 30 s dedup it did not change VLM triggers ({0} vs {1});".format(
            "/".join(map(str, full)), "/".join(str(by[(n, 'no_temporal')]["vlm_triggers"]) for n in names)),
        "  it reduced candidates before dedup ({0} with vs {1} without).".format(
            "/".join(str(by[(n, 'full')]["candidates_raised"]) for n in names),
            "/".join(str(by[(n, 'no_temporal')]["candidates_raised"]) for n in names)),
        "- Coverage cost of dedup: every target-colour vehicle that entered the view produced Full",
        "  candidates, but only {0} of {1} distinct target vehicles reached a VLM trigger in Full".format(
            "/".join(str(by[(n, 'full')]["target_actors_with_vlm_trigger"]) for n in names),
            "/".join(str(by[(n, 'full')]["target_color_vehicles_entering_fov"]) for n in names)),
        "  (No Dedup: {0}); vehicles arriving within 30 s of a previous trigger were suppressed.".format(
            "/".join(str(by[(n, 'no_dedup')]["target_actors_with_vlm_trigger"]) for n in names)),
        "- Production behaviour observed (not changed): TemporalConfirm is called for tracks not",
        "  matched in the current frame, so a stale track can be confirmed and its old bbox cropped",
        "  from the current frame (run 3: {0} of {1} Full triggers; e.g. `evidence/runs/run2/trigger_crops/full/f1300_t77.jpg`".format(
            by[("run3", "full")]["vlm_triggers_from_disappeared_tracks"], by[("run3", "full")]["vlm_triggers"]),
        "  shows empty road). Occlusion by a blue/red street banner also produced a false-blue",
        "  candidate on a yellow car (`evidence/runs/run2/trigger_crops/full/f1877_t134.jpg`).",
        "", "Full limitations: `limitations.md`.", "", END,
    ]
    return "\n".join(lines)


def main():
    runs = [load_run(*spec) for spec in RUNS]
    rows = build_rows(runs)
    with (HERE / "runs_comparison.csv").open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    report_path = HERE / "continuous_10min_report.md"
    report = report_path.read_text(encoding="utf-8")
    generated = section(runs, rows)
    if BEGIN in report:
        report = report[:report.index(BEGIN)] + generated + report[report.index(END) + len(END):]
    else:
        anchor = "## Ablation comparison"
        report = report.replace(anchor, generated + "\n\n" + anchor, 1)
    report_path.write_text(report, encoding="utf-8")
    print("\n".join(generated.splitlines()[1:40]))


if __name__ == "__main__":
    main()
